/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baishengye_liblame_LameLoader */

#ifndef _Included_com_baishengye_liblame_LameLoader
#define _Included_com_baishengye_liblame_LameLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baishengye_liblame_LameLoader
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baishengye_liblame_LameLoader_getLameVersion
        (JNIEnv *, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
