/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baishengye_liblame_LameLoader */

#ifndef _Included_com_baishengye_liblame_LameLoader
#define _Included_com_baishengye_liblame_LameLoader
#ifdef __cplusplus
extern "C" {
#endif

/*获取Lame版本号*/
JNIEXPORT jstring JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_getLameVersion(JNIEnv *env, jobject clazz);


/*默认方式初始化Lame*/
JNIEXPORT jint JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_initLameDefault(JNIEnv *env, jobject clazz);

/*配置参数初始化Lame*/
JNIEXPORT jint JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_initLame(JNIEnv *env, jobject clazz,
                                                               jint in_sample_rate,
                                                               jint out_channel,
                                                               jint out_sample_rate,
                                                               jint out_bitrate,
                                                               jfloat scale_input,
                                                               jint mode,
                                                               jint vbr_mode,
                                                               jint quality,
                                                               jint vbr_quality,
                                                               jint abr_mean_bitrate,
                                                               jint lowpass_freq,
                                                               jint highpass_freq,
                                                               jstring id3tag_title,
                                                               jstring id3tag_artist,
                                                               jstring id3tag_album,
                                                               jstring id3tag_year,
                                                               jstring id3tag_comment);


/*回收lame的编码缓冲区*/
JNIEXPORT jint JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_lameEncodeFlush(JNIEnv *env, jobject clazz,
                                                                      jbyteArray mp3buf);


/*编码*/
JNIEXPORT jint JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_lameEncodeBuffer(JNIEnv *env, jobject clazz,
                                                                       jshortArray buffer_l,
                                                                       jshortArray buffer_r,
                                                                       jint samples,
                                                                       jbyteArray mp3buf);

/*左右声道混合编码*/
JNIEXPORT jint JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_lameEncodeBufferInterleaved(JNIEnv *env,
                                                                                  jobject clazz,
                                                                                  jshortArray pcm,
                                                                                  jint samples,
                                                                                  jbyteArray mp3buf);

/*销毁Lame*/
JNIEXPORT void JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_lameClose(JNIEnv *env, jobject clazz);

JNIEXPORT void JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_wav2mp3(JNIEnv *env, jobject clazz,
                                                              jstring wav_path, jstring mp3_path);


JNIEXPORT void JNICALL
Java_com_baishengye_liblame_LameLoader_00024Companion_wav2mp3Speed(JNIEnv *env, jobject thiz,
                                                                   jstring wav_path,
                                                                   jstring mp3_path, jint speed);
#ifdef __cplusplus
}
#endif
#endif