/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class baishengye_liblame_LameLoader */

#ifndef _Included_baishengye_liblame_LameLoader
#define _Included_baishengye_liblame_LameLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef baishengye_liblame_LameLoader_MP3_BUFFER_SIZE
#define baishengye_liblame_LameLoader_MP3_BUFFER_SIZE 1024L
#undef baishengye_liblame_LameLoader_LAME_PRESET_DEFAULT
#define baishengye_liblame_LameLoader_LAME_PRESET_DEFAULT 0L
#undef baishengye_liblame_LameLoader_LAME_PRESET_MEDIUM
#define baishengye_liblame_LameLoader_LAME_PRESET_MEDIUM 1L
#undef baishengye_liblame_LameLoader_LAME_PRESET_STANDARD
#define baishengye_liblame_LameLoader_LAME_PRESET_STANDARD 2L
#undef baishengye_liblame_LameLoader_LAME_PRESET_EXTREME
#define baishengye_liblame_LameLoader_LAME_PRESET_EXTREME 3L

/**
 * 获取Lame版本号
 * @return 版本号*/
JNIEXPORT jstring JNICALL
Java_com_baishengye_liblame_LameLoader_getLameVersion(JNIEnv *env, jobject clazz);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_initializeEncoder
        (JNIEnv *, jobject, jint, jint, jint out_sample_rate, jint out_bitrate, jint quality);


JNIEXPORT void JNICALL Java_com_baishengye_liblame_LameLoader_setEncoderPreset
        (JNIEnv *, jobject, jint);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_encode
        (JNIEnv *, jobject, jshortArray, jshortArray, jint, jbyteArray, jint);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_flushEncoder
        (JNIEnv *, jobject, jbyteArray, jint);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_closeEncoder
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_baishengye_liblame_LameLoader_wav2mp3(JNIEnv *env, jobject clazz,
                                                                      jstring wav_path,
                                                                      jstring mp3_path);

JNIEXPORT void JNICALL
Java_com_baishengye_liblame_LameLoader_wav2mp3Speed(JNIEnv *env, jobject clazz,
                                                    jstring wav_path,
                                                    jstring mp3_path, jint speed);

/********************************************下面解码操作***********************************************************************/

JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_initializeDecoder
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderSampleRate
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderChannels
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderDelay
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderPadding
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderTotalFrames
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderFrameSize
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_getDecoderBitrate
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_nativeConfigureDecoder
        (JNIEnv *, jobject, jbyteArray, jint);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_nativeDecodeFrame
        (JNIEnv *, jobject, jbyteArray, jint, jshortArray, jshortArray);


JNIEXPORT jint JNICALL Java_com_baishengye_liblame_LameLoader_closeDecoder
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
